const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const assert=(c,m)=>{if(!c)throw new Error('Hotfix 17 contract: '+m)};
const server=read('server.js');
const engine=read('public/estudex-engine.js');
const pkg=JSON.parse(read('package.json'));
const forge=read('forge.config.js');
const manifest=JSON.parse(read('estudex-hotfix17-manifest.json'));
assert(pkg.version==='1.9.21','package version must be 1.9.21');
assert(/version:\s*["']1\.9\.21["']/.test(forge),'Squirrel version must be 1.9.21');
assert(server.includes('ESTUDEX_V193_HOTFIX17_AUTHORITATIVE_PRESENCE'),'Hotfix 17 marker missing');
assert(server.includes("path.join(process.env.LOCALAPPDATA || '', 'Famatech', 'Radmin VPN', 'phonebook.rpb')"),'Radmin phonebook path missing');
assert(server.includes("buffer.toString('utf16le')"),'UTF-16LE phonebook scan missing');
assert(server.includes("'radmin-phonebook-rpb'"),'phonebook diagnostic source missing');
assert(server.includes('estudexDirectIdentifyStrictV197'),'strict direct identity proof missing');
assert(server.includes("fetch('http://' + ip + ':8787/api/social/direct-identify?_=' + Date.now()"),'fresh TCP 8787 proof request missing');
assert(server.includes('ESTUDEX_PRESENCE_ONLINE_TTL_V197 = 7500'),'online TTL must be 7.5 seconds');
assert(server.includes('ESTUDEX_PRESENCE_OFFLINE_RETAIN_V197 = 60000'),'offline retention must be 60 seconds');
assert(server.includes('estudexPresenceByIdV197'),'authoritative presence registry missing');
assert(server.includes('estudexLanSnapshotAuthoritativeV197'),'authoritative LAN snapshot missing');
assert(server.includes("app.get('/api/social/presence-debug'"),'diagnostic endpoint missing');
assert(server.includes("discovery:deep?'authoritative-presence-v197-deep':'authoritative-presence-v197'"),'lan-peers discovery marker missing');
assert(engine.includes('ESTUDEX_V193_HOTFIX17_AUTHORITATIVE_PRESENCE_UI'),'renderer authoritative marker missing');
assert(manifest.presence?.radminRole==='candidate transport only','Radmin role contract wrong');
assert(manifest.presence?.authority==='server presence registry keyed by ESTUDEX user id','presence authority contract wrong');
assert(manifest.discovery?.diagnosticRoute==='/api/social/presence-debug','diagnostic route manifest wrong');
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
assert(sha('public/js/home.js')===manifest.canonicalHome.js,'canonical home.js changed');
assert(sha('public/css/home.css')===manifest.canonicalHome.css,'canonical home.css changed');
console.log('Hotfix 17 authoritative presence contracts passed.');
