const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const assert=(c,m)=>{if(!c)throw new Error('Hotfix 17 contract: '+m)};
const server=read('server.js');
const engine=read('public/estudex-engine.js');
const pkg=JSON.parse(read('package.json'));
const forge=read('forge.config.js');
const manifest=JSON.parse(read('estudex-hotfix17-manifest.json'));
assert(pkg.version==='1.9.21','package version must be 1.9.21');
assert(/version:\s*["']1\.9\.21["']/.test(forge),'Squirrel version must be 1.9.21');
assert(server.includes('ESTUDEX_V193_HOTFIX17_AUTHORITATIVE_PRESENCE'),'server Hotfix 17 marker missing');
assert(server.includes("path.join(process.env.LOCALAPPDATA || '', 'Famatech', 'Radmin VPN', 'phonebook.rpb')"),'Radmin phonebook path missing');
assert(server.includes("buffer.toString('utf16le')"),'UTF-16LE phonebook scan missing');
assert(server.includes('ESTUDEX_PRESENCE_ONLINE_TTL_V197 = 7500'),'online TTL must be 7.5 seconds');
assert(server.includes('ESTUDEX_PRESENCE_OFFLINE_RETAIN_V197 = 60000'),'offline retention must be 60 seconds');
assert(server.includes('estudexPresenceDirectoryV197'),'authoritative presence directory missing');
assert(server.includes("url.pathname === '/api/social/presence-debug'"),'HTTP presence diagnostic route missing');
assert(server.includes("discovery:deep?'authoritative-presence-v197-deep':'authoritative-presence-v197'"),'lan-peers discovery marker missing');
assert(engine.includes('ESTUDEX_V193_HOTFIX17_AUTHORITATIVE_PRESENCE_UI'),'renderer marker missing');
assert(engine.includes('.map(user=>normalizeFriend({...user,online:Boolean(user?.online)}))'),'listPeers must preserve server online value');
assert(!engine.includes('.map(user=>normalizeFriend({...user,online:true}))'),'listPeers must not force every server peer online');
assert(engine.includes('friend.online=Boolean(live?.online)&&'),'friend refresh must require authoritative peer.online');
assert(engine.includes('const publicOnline = Boolean(peer?.online) && isPublicOnlineV194(friend.status);'),'friend reconciliation must require peer.online');
assert(engine.includes('friend.online = Boolean(peer?.online) && isPublicOnlineV194(peer.status || friend.status);'),'stored friend healing must require peer.online');
assert(manifest.presence?.radminRole==='candidate transport only','Radmin role contract wrong');
assert(manifest.presence?.authority==='server directory keyed by ESTUDEX user id','presence authority contract wrong');
assert(manifest.discovery?.diagnosticRoute==='/api/social/presence-debug','diagnostic route manifest wrong');
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
assert(sha('public/js/home.js')===manifest.canonicalHome.js,'canonical home.js changed');
assert(sha('public/css/home.css')===manifest.canonicalHome.css,'canonical home.css changed');
console.log('Hotfix 17 authoritative presence contracts passed.');
