'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=r=>fs.readFileSync(path.join(root,r),'utf8');
const write=(r,t)=>fs.writeFileSync(path.join(root,r),t,'utf8');
const sha=r=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,r))).digest('hex');
const must=(v,m)=>{if(!v)throw new Error('Hotfix33: '+m)};
const pkgPath=path.join(root,'package.json');
const pkg=JSON.parse(fs.readFileSync(pkgPath,'utf8'));
must(pkg.version==='1.9.36','expected 1.9.36 baseline');
must(fs.existsSync(path.join(root,'estudex-hotfix32-manifest.json')),'Hotfix32 manifest missing');
const homeJs=sha('public/js/home.js'),homeCss=sha('public/css/home.css');
let compat=read('public/js/estudex-engine-socket-compat.js');
must(compat.includes('ESTUDEX_V193_HOTFIX32_CREATE_FEEDBACK'),'Hotfix32 baseline missing');
must(!compat.includes('ESTUDEX_V193_HOTFIX33_SINGLE_OWNED_ROOM_OVERLAY'),'already patched');
const from="    if(revive)deletedOwnedRooms.delete(card.code);\n    const previous=pinnedOwnedRooms.get(card.code);";
const to="    if(revive)deletedOwnedRooms.delete(card.code);\n    /* ESTUDEX_V193_HOTFIX33_SINGLE_OWNED_ROOM_OVERLAY */\n    if(active){\n      for(const code of [...pinnedOwnedRooms.keys()]){\n        if(code===card.code)continue;\n        pinnedOwnedRooms.delete(code);\n        liveRoomGrace.delete(code);\n        deletedOwnedRooms.add(code);\n      }\n    }\n    const previous=pinnedOwnedRooms.get(card.code);";
must(compat.split(from).length===2,'owned-room anchor mismatch');
compat=compat.replace(from,to);
write('public/js/estudex-engine-socket-compat.js',compat);
pkg.version='1.9.37';
fs.writeFileSync(pkgPath,JSON.stringify(pkg,null,2)+'\n','utf8');
let forge=read('forge.config.js');
must(/version:\s*["']1\.9\.36["']/.test(forge),'forge version anchor missing');
forge=forge.replace(/version:\s*["']1\.9\.36["']/,'version: "1.9.37"');
write('forge.config.js',forge);
const manifest={product:'ESTUDEX',productVersion:'1.9.3',technicalVersion:'1.9.37',hotfix:33,baseTag:'v1.9.36-hotfix32',fixes:['single active owned-room overlay','superseded owned-room grace entries are tombstoned'],backend:{minimumVersion:'0.3.8',oneActiveHostedRoomPerUser:true,persistence:'supabase'},preserved:{homeJs,homeCss}};
fs.writeFileSync(path.join(root,'estudex-hotfix33-manifest.json'),JSON.stringify(manifest,null,2)+'\n','utf8');
must(sha('public/js/home.js')===homeJs,'home.js changed');
must(sha('public/css/home.css')===homeCss,'home.css changed');
console.log('ESTUDEX Hotfix33 applied');
