'use strict';
const fs=require('fs'),path=require('path');
const root=path.resolve(process.argv[2]||process.cwd());
const read=r=>fs.readFileSync(path.join(root,r),'utf8');
const must=(v,m)=>{if(!v)throw new Error('Hotfix34 contract: '+m)};
const pkg=JSON.parse(read('package.json'));
must(pkg.version==='1.9.38','version');
const manifest=JSON.parse(read('estudex-hotfix34-manifest.json'));
must(manifest.hotfix===34,'manifest');
const home=read('public/js/home.js');
const main=read('main.js');
const compat=read('public/js/estudex-engine-socket-compat.js');
must(home.includes('ESTUDEX_V193_HOTFIX34_ROOM_PAINT_COALESCE'),'room paint marker');
must(home.includes("scheduleTransmissionRoomRenderV1938('showPage')"),'showPage scheduled render');
must(home.includes("scheduleTransmissionRoomRenderV1938('room:state')"),'room state scheduled render');
must(!home.includes('socket.emit("room:request-state");\n  renderTransmissionRoom();'),'room joined duplicate render still present');
must(main.includes('ESTUDEX_V193_HOTFIX34_LOOPBACK_UI_SERVER'),'loopback marker');
must(main.includes("host: '127.0.0.1'"),'loopback host');
must(!main.includes("host: '0.0.0.0'"),'wildcard listener remains');
must(compat.includes('ESTUDEX_V193_HOTFIX33_SINGLE_OWNED_ROOM_OVERLAY'),'Hotfix33 preserved');
console.log('Hotfix34 contract OK');
