'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const must=(v,m)=>{if(!v)throw new Error('ESTUDEX Hotfix 30 contract: '+m);};
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
const OFFICIAL='https://site--estudex-server--bs292kkyk4sm.code.run';
const pkg=JSON.parse(read('package.json'));
must(pkg.version==='1.9.34','package version must be 1.9.34');
const manifest=JSON.parse(read('estudex-hotfix30-manifest.json'));
must(manifest.hotfix===30&&manifest.technicalVersion==='1.9.34','manifest version mismatch');
must(manifest.backend?.version==='0.3.4','backend contract must be 0.3.4');
const cloud=read('public/js/estudex-v193-cloud-social-v1926.js');
must(cloud.includes('ESTUDEX_V193_HOTFIX30_RESILIENT_BACKEND'),'resilient backend marker missing');
must(cloud.includes(`const DEFAULT_BASE = '${OFFICIAL}'`),'official auth backend fallback missing');
must(cloud.includes("friendly.code='backend_unreachable'"),'friendly transport error missing');
must(cloud.includes('async function probeBase'),'backend health probe missing');
must(cloud.includes("version:'1.9.30'"),'cloud API version missing');
must(!cloud.includes("const DEFAULT_BASE = 'https://estudexserver-2mccfr6f.b4a.run'"),'obsolete auth fallback still active');
const engine=read('public/estudex-engine.js');
must(engine.includes(`const ESTUDEX_CLOUD_ROOM_DEFAULT_V1924 = '${OFFICIAL}'`),'room fallback not aligned');
must(engine.includes("error?.code==='host_room_exists'"),'duplicate-host reconnect guard missing');
must(engine.includes('joinError.roomId=msg.roomId'),'room error metadata missing');
const forge=read('forge.config.js');
must(/version:\s*["']1\.9\.34["']/.test(forge),'forge version must be 1.9.34');
must(sha('public/js/home.js')===manifest.preserved.homeJs,'canonical home.js hash changed');
must(sha('public/css/home.css')===manifest.preserved.homeCss,'canonical home.css hash changed');
console.log('ESTUDEX Hotfix 30 contract OK');
