'use strict';
const fs=require('fs');
const path=require('path');
const root=path.resolve(process.argv[2]||process.cwd());
const must=(ok,msg)=>{if(!ok)throw new Error('ESTUDEX Hotfix 29 contract: '+msg);};
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const pkg=JSON.parse(read('package.json'));
must(pkg.version==='1.9.33','package version must be 1.9.33');
const forge=read('forge.config.js');must(/version:\s*["']1\.9\.33["']/.test(forge),'Squirrel version must be 1.9.33');
const engine=read('public/estudex-engine.js');
must(engine.includes('ESTUDEX_V193_HOTFIX29_ROOM_RECONNECT'),'room reconnect marker missing');
must(engine.includes("'recoverRemote','onChange'"),'recoverRemote public facade missing');
must(engine.includes("sessionToken:String(root.EstudexCloudSocial?.getSessionToken?.() || '')"),'verified room join token missing');
must(engine.includes("msg.type === 'member-identity'"),'member identity handler missing');
must(engine.includes("emitRoom('reconnected'"),'room reconnected event missing');
const cloud=read('public/js/estudex-v193-cloud-social-v1926.js');
must(cloud.includes('ESTUDEX_V193_HOTFIX29_LIVE_ROOM_DIRECTORY'),'live room directory marker missing');
must(cloud.includes("request('/api/rooms/live'"),'live room endpoint missing');
must(cloud.includes('getSessionToken:()=>state.token'),'cloud session token bridge missing');
const compat=read('public/js/estudex-engine-socket-compat.js');must(compat.includes('userId:clean(member?.userId'),'legacy room member user id missing');
const runtime=read('public/js/estudex-v193-hotfix29-room-network.js');must(runtime.includes('ESTUDEX_V193_HOTFIX29_ROOM_SOCIAL_RUNTIME'),'room social runtime missing');must(runtime.includes('sendFriendRequest(target)'),'in-room friend action missing');
const index=read('public/index.html');must(index.includes('/js/estudex-v193-hotfix29-room-network.js'),'Hotfix 29 runtime not loaded');
const manifest=JSON.parse(read('estudex-hotfix29-manifest.json'));must(manifest.technicalVersion==='1.9.33'&&manifest.hotfix===29,'manifest revision mismatch');
console.log('ESTUDEX Hotfix 29 contract OK.');
