const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const must=(c,m)=>{if(!c)throw new Error('ESTUDEX Hotfix 20 contract: '+m)};
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
const engine=read('public/estudex-engine.js');
const compat=read('public/js/estudex-engine-socket-compat.js');
const pkg=JSON.parse(read('package.json'));
const forge=read('forge.config.js');
const manifest=JSON.parse(read('estudex-hotfix20-manifest.json'));
must(pkg.version==='1.9.24','package version');
must(/version:\s*["']1\.9\.24["']/.test(forge),'forge version');
must(engine.includes('ESTUDEX_V193_HOTFIX20_CLOUD_ROOM_TEST'),'cloud marker missing');
must(engine.includes('https://estudexserver-p1t0c2xc.b4a.run'),'cloud base missing');
must(engine.includes("stun:stun.l.google.com:19302"),'STUN missing');
must(engine.includes("await connectRoom({room,role:'host',signalingBase:endpoint,name,limit});"),'cloud host join path missing');
must(engine.includes("candidate = {...candidate, hostEndpoint:estudexCloudRoomBaseV1924()};"),'cloud viewer endpoint missing');
must(engine.includes("hostEndpoint:roomState.signalingBase,"),'saved room cloud endpoint missing');
must(compat.includes('Hotfix 20: cloud room tests do not require Radmin.'),'room Radmin gate still active');
must(engine.includes("type:'media-signal'"),'media signaling removed');
must(engine.includes("type:'join'"),'room join protocol removed');
must(manifest.cloud?.media==='WebRTC P2P','manifest media mode');
must(manifest.radminRequiredForRooms===false,'manifest Radmin room flag');
must(sha('public/js/home.js')===manifest.canonicalHome.js,'canonical home.js changed');
must(sha('public/css/home.css')===manifest.canonicalHome.css,'canonical home.css changed');
console.log('ESTUDEX Hotfix 20 cloud friends-test contract passed.');
