const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const assert=(c,m)=>{if(!c)throw new Error('Hotfix 15 contract: '+m)};
const server=read('server.js');
const engine=read('public/estudex-engine.js');
const pkg=JSON.parse(read('package.json'));
const forge=read('forge.config.js');
const manifest=JSON.parse(read('estudex-hotfix15-manifest.json'));
assert(pkg.version==='1.9.19','package version must be 1.9.19');
assert(/version:\s*["']1\.9\.19["']/.test(forge),'Squirrel version must be 1.9.19');
assert(server.includes('ESTUDEX_V193_HOTFIX15_PROOF_HYBRID_PRESENCE'),'server marker missing');
assert(server.includes('estudexRadminNeighborIpsV170()'),'neighbour discovery missing');
assert(server.includes('estudexDirectIdentifyV170(ip)'),'direct ESTUDEX proof missing');
assert(server.includes("presenceProof:'direct-identify-v195'"),'direct proof marker missing');
assert(server.includes("presenceProof:'verified-beacon-v195'"),'verified beacon proof marker missing');
assert(server.includes('const ESTUDEX_LAN_VERIFY_TTL_V187 = 4000;'),'verification cache must be 4 seconds');
assert(server.includes("discovery:deep?'proof-hybrid-v195-deep':'proof-hybrid-v195'"),'route must expose hybrid proof discovery');
assert(engine.includes('ESTUDEX_V193_HOTFIX15_PROOF_PRESENCE_UI'),'renderer marker missing');
assert(engine.includes('const RADMIN_PEER_GRACE_MS_V194 = 9000;'),'peer grace must be 9 seconds');
assert(manifest.presence?.radminIsTransportOnly===true,'Radmin must remain transport only');
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
assert(sha('public/js/home.js')===manifest.canonicalHome.js,'canonical home.js changed');
assert(sha('public/css/home.css')===manifest.canonicalHome.css,'canonical home.css changed');
console.log('Hotfix 15 presence contracts passed.');
