const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const root = path.resolve(process.argv[2] || process.cwd());
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
const exists = rel => fs.existsSync(path.join(root, rel));
const sha = rel => crypto.createHash('sha256').update(fs.readFileSync(path.join(root, rel))).digest('hex');
const must = (condition, message) => { if (!condition) throw new Error('ESTUDEX Hotfix 22 contract: ' + message); };

const pkg = JSON.parse(read('package.json'));
const forge = read('forge.config.js');
const engine = read('public/estudex-engine.js');
const index = read('public/index.html');
const preload = read('preload.js');
const main = read('main.js');
const localServer = read('server.js');
const settings = read('public/js/estudex-v193-spec-settings.js');
const bindings = read('public/js/estudex-engine-data-bindings.js');
const socketCompat = read('public/js/estudex-engine-socket-compat.js');
const roomActions = read('public/js/estudex-v193-room-actions-hotfix.js');
const cloud = read('public/js/estudex-v193-cloud-social-v1926.js');
const manifest = JSON.parse(read('estudex-hotfix22-manifest.json'));

must(pkg.version === '1.9.26', 'package version');
must(/version:\s*["']1\.9\.26["']/.test(forge), 'forge version');
must(engine.includes('ESTUDEX_V193_HOTFIX20_CLOUD_ROOM_TEST'), 'cloud room baseline missing');
must(engine.includes('ESTUDEX_V193_HOTFIX21_SYSTEM_AUDIO'), 'screen audio baseline missing');
must(cloud.includes('ESTUDEX_V193_HOTFIX22_CLOUD_SOCIAL'), 'cloud social runtime marker missing');
must(cloud.includes('/api/auth/guest') && cloud.includes('/api/auth/login') && cloud.includes('/api/auth/register'), 'auth client endpoints missing');
must(cloud.includes('/api/users/search?q=') && cloud.includes('/api/friends/requests') && cloud.includes('/api/dm/'), 'social client endpoints missing');
must(cloud.includes('sendRoomInvite') && cloud.includes('respondRoomInvite'), 'room invite client API missing');
must(cloud.includes('config/estudex-cloud.json'), 'remote endpoint config missing');
must(index.includes('/js/estudex-v193-cloud-social-v1926.js'), 'cloud social script not loaded');
must(!/radmin/i.test(index), 'Radmin still visible in index');
must(!/radmin/i.test(settings), 'Radmin settings still present');
must(!/radmin/i.test(preload), 'Radmin renderer/native bridge still exposed');
must(!/radmin/i.test(bindings), 'Radmin social data binding still active');
must(!/radmin/i.test(socketCompat), 'Radmin socket compatibility wording/data still present');
must(!exists('public/js/estudex-v193-spec-radmin.js'), 'obsolete Radmin renderer binding still packaged');
must(main.includes('safeStorage') && main.includes('estudex:auth-session:get-v1926') && main.includes('estudex:auth-session:set-v1926'), 'secure native session bridge missing');
must(localServer.includes('ESTUDEX_V193_HOTFIX22_CLOUD_ONLY_SOCIAL_TRANSPORT'), 'legacy LAN responder was not disabled');
must(roomActions.includes('EstudexCloudSocial?.sendRoomInvite') && roomActions.includes("respondRoomInvite(id,'accept')"), 'cloud room invite flow missing');
const direct = engine.slice(engine.indexOf('/* ESTUDEX_V193_SPEC_DIRECT_CALL_ENGINE */'));
must(direct.includes('sendSocialEvent') && direct.includes('listSocialEvents'), 'private calls are not using cloud social signaling');
must(!direct.includes('/api/social/message') && !direct.includes('/api/social/inbox'), 'private calls still use local/Radmin social endpoints');
must(!direct.includes('iceServers:[]'), 'private calls still have empty ICE config');
must(direct.includes('stun:stun.l.google.com:19302') && direct.includes('stun:stun1.l.google.com:19302'), 'private call STUN missing');
must(manifest.backend?.serverVersion === '0.3.0', 'manifest server version');
must(manifest.identity?.guestPersistent === true, 'persistent Guest manifest flag');
must(manifest.network?.radminRendererBridgeRemoved === true, 'Radmin bridge manifest flag');
must(manifest.network?.turnConfigured === false, 'TURN status must remain explicit');
must(sha('public/js/home.js') === manifest.canonicalHome.js, 'canonical V10.10 home.js changed');
must(sha('public/css/home.css') === manifest.canonicalHome.css, 'canonical V10.10 home.css changed');
console.log('ESTUDEX Hotfix 22 cloud social contract passed.');
