const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const must=(c,m)=>{if(!c)throw new Error('ESTUDEX Hotfix 21 contract: '+m)};
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
const engine=read('public/estudex-engine.js');
const pkg=JSON.parse(read('package.json'));
const forge=read('forge.config.js');
const manifest=JSON.parse(read('estudex-hotfix21-manifest.json'));
must(pkg.version==='1.9.25','package version');
must(/version:\s*["']1\.9\.25["']/.test(forge),'forge version');
must(engine.includes('ESTUDEX_V193_HOTFIX20_CLOUD_ROOM_TEST'),'Hotfix 20 cloud baseline missing');
must(engine.includes('ESTUDEX_V193_HOTFIX21_SYSTEM_AUDIO'),'system-audio marker missing');
must(engine.includes("audio:{mandatory:{chromeMediaSource:'desktop'}}"),'desktop loopback constraint missing');
must(engine.includes('await estudexAttachSystemAudioV1925(stream, mediaState.audioEnabled);'),'room share loopback attach missing');
must(engine.includes('await estudexAttachSystemAudioV1925(screenStream, state.audioEnabled);'),'direct call loopback attach missing');
must(engine.includes("for(const track of screenStream?.getAudioTracks?.()||[])track.enabled=state.audioEnabled"),'direct call audio toggle missing');
must(engine.includes('__estudexSystemAudioWrappedV1925'),'getDisplayMedia compatibility wrapper missing');
must(engine.includes("stun:stun.l.google.com:19302"),'cloud STUN missing');
must(manifest.screenAudio?.capture==='system-loopback','manifest loopback mode');
must(manifest.screenAudio?.fallback==='video-only-if-loopback-unavailable','manifest fallback mode');
must(sha('public/js/home.js')===manifest.canonicalHome.js,'canonical home.js changed');
must(sha('public/css/home.css')===manifest.canonicalHome.css,'canonical home.css changed');
console.log('ESTUDEX Hotfix 21 system-audio contract passed.');
