const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const assert=(c,m)=>{if(!c)throw new Error('Hotfix 16 contract: '+m)};
const server=read('server.js');
const pkg=JSON.parse(read('package.json'));
const forge=read('forge.config.js');
const manifest=JSON.parse(read('estudex-hotfix16-manifest.json'));
assert(pkg.version==='1.9.20','package version must be 1.9.20');
assert(/version:\s*["']1\.9\.20["']/.test(forge),'Squirrel version must be 1.9.20');
assert(server.includes('ESTUDEX_V193_HOTFIX16_RADMIN_MEMBER_CANDIDATES'),'Hotfix 16 marker missing');
assert(server.includes('estudexRadminCandidateIpsV196()'),'candidate collector missing');
assert(server.includes('estudexRadminUiIpsV196()'),'Radmin UI candidate source missing');
assert(server.includes('UIAutomationClient'),'Windows UI Automation source missing');
assert(server.includes('estudexRadminNeighborIpsV170()'),'Windows neighbour source missing');
assert(server.includes('estudexRadminLocalFileIpsV196()'),'Radmin local file source missing');
assert(server.includes("estudexExecHiddenV170('netstat.exe'"),'netstat candidate source missing');
assert(server.includes('estudexKnownStateIpsV196'),'known ESTUDEX endpoint source missing');
assert(server.includes('estudexRememberRadminIpV196'),'verified candidate persistence missing');
assert(server.includes('estudexDirectIdentifyV170(ip)'),'direct ESTUDEX proof missing');
assert(server.includes("presenceProof:'direct-identify-v196'"),'direct proof version missing');
assert(server.includes("discovery:deep?'radmin-member-proof-v196-deep':'radmin-member-proof-v196'"),'diagnostic source missing');
assert(manifest.discovery?.onlineProof==='TCP 8787 /api/social/direct-identify only','online proof contract wrong');
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
assert(sha('public/js/home.js')===manifest.canonicalHome.js,'canonical home.js changed');
assert(sha('public/css/home.css')===manifest.canonicalHome.css,'canonical home.css changed');
console.log('Hotfix 16 discovery contracts passed.');
