'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
const must=(ok,msg)=>{if(!ok)throw new Error('ESTUDEX Hotfix31 contract: '+msg);};
const pkg=JSON.parse(read('package.json'));
must(pkg.version==='1.9.35','package version must be 1.9.35');
must(/version:\s*["']1\.9\.35["']/.test(read('forge.config.js')),'forge version must be 1.9.35');
const manifest=JSON.parse(read('estudex-hotfix31-manifest.json'));
must(manifest.hotfix===31&&manifest.technicalVersion==='1.9.35','manifest mismatch');
const cloud=read('public/js/estudex-v193-cloud-social-v1926.js');
must(cloud.includes('ESTUDEX_V193_HOTFIX31_SIMPLE_HANDLE_UI'),'simple handle marker missing');
must(cloud.includes("request('/api/auth/quick'"),'quick identity endpoint missing');
must(cloud.includes("version:'1.9.31'"),'cloud API version missing');
must(cloud.includes('EstudexNative?.cloud?.request'),'native-first cloud request missing');
must(cloud.includes('ESTUDEX_V193_HOTFIX31_DISABLE_ACCOUNT_UPGRADE_UI'),'old account upgrade UI not disabled');
must(!cloud.includes('id="cloudLoginForm"'),'login form still visible in onboarding');
must(!cloud.includes('id="cloudRegisterForm"'),'register form still visible in onboarding');
must(!cloud.includes('id="cloudGuestForm"'),'guest form still visible in onboarding');
must(cloud.includes('Escolha seu @usuário'),'simple onboarding copy missing');
must(cloud.includes("addInput.placeholder='@usuario'"),'@ friend search placeholder missing');
const main=read('main.js');
must(main.includes('ESTUDEX_V193_HOTFIX31_NATIVE_CLOUD_TRANSPORT'),'main native transport missing');
must(main.includes("ipcMain.handle('estudex:cloud-request-v1935'"),'main cloud IPC missing');
must(main.includes("const https = require('https');"),'https transport missing');
const preload=read('preload.js');
must(preload.includes("ipcRenderer.invoke('estudex:cloud-request-v1935'"),'preload cloud bridge missing');
must(sha('public/js/home.js')===manifest.preserved.homeJs,'canonical home.js changed');
must(sha('public/css/home.css')===manifest.preserved.homeCss,'canonical home.css changed');
console.log('ESTUDEX Hotfix31 contract OK.');
