'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const sha=rel=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,rel))).digest('hex');
const must=(ok,msg)=>{if(!ok)throw new Error('ESTUDEX Hotfix32 contract: '+msg);};
const pkg=JSON.parse(read('package.json'));
must(pkg.version==='1.9.36','package version must be 1.9.36');
must(/version:\s*["']1\.9\.36["']/.test(read('forge.config.js')),'forge version must be 1.9.36');
const manifest=JSON.parse(read('estudex-hotfix32-manifest.json'));
must(manifest.hotfix===32&&manifest.technicalVersion==='1.9.36','manifest mismatch');
const engine=read('public/estudex-engine.js');
must(engine.includes('ESTUDEX_V193_HOTFIX32_ROOM_INPUT_LATENCY'),'engine latency marker missing');
must(engine.includes('const ROOM_RECONNECT_DELAYS=[0,350,900,1800];'),'immediate reconnect schedule missing');
must(engine.includes('signalingBase = estudexCloudRoomBaseV1924();'),'fast host endpoint missing');
const cloud=read('public/js/estudex-v193-cloud-social-v1926.js');
must(cloud.includes('ESTUDEX_V193_HOTFIX32_INLINE_ROOM_STATUS'),'inline status marker missing');
must(cloud.includes('statusInline===true'),'inline status consumption missing');
must(!cloud.includes("request('/api/rooms/saved/status?room='+encodeURIComponent(r.room)"),'per-room saved status N+1 request still present');
must(cloud.includes('ESTUDEX_V193_HOTFIX32_SESSION_PRESERVATION'),'session preservation marker missing');
must(cloud.includes("error?.code==='saved_session_pending'&&state.token"),'saved profile startup guard missing');
must(cloud.includes("status===401||status===403||code==='invalid_session'||code==='auth_required'"),'explicit invalid-session gate missing');
must(!cloud.includes('catch{await clearToken();return false;}'),'destructive restoreSession catch still present');
must(cloud.includes("version:'1.9.32'"),'cloud API version missing');
const compat=read('public/js/estudex-engine-socket-compat.js');
must(compat.includes('ESTUDEX_V193_HOTFIX32_CREATE_FEEDBACK'),'create feedback marker missing');
must(compat.includes('createRoomInFlightV1936'),'create duplicate guard missing');
must(compat.includes("createButton.textContent='Criando...'"),'instant create feedback missing');
must(compat.includes('ESTUDEX_V193_RECENT_ROOM_COMPAT_FAST_PATH'),'same-room navigation fast path lost');
must(sha('public/js/home.js')===manifest.preserved.homeJs,'canonical home.js changed');
must(sha('public/css/home.css')===manifest.preserved.homeCss,'canonical home.css changed');
console.log('ESTUDEX Hotfix32 contract OK.');
